version: '3.8 '

services:
  mysql:
    image: mysql:8.0.43
    container_name: mysql_pb
    ports:
      "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
